# Custom Language File for Launcher Customizer

[ejs.app]
title = "영콘 월드"

[ejs.landing]
mediaGitHubURL = "https://github.com/CustomLauncherLab/VCWorld"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/Cb9Wx8HRU4"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/VCWorld"
supportLink = "https://github.com/CustomLauncherLab/VCWorld/issues"

[ejs.welcome]
welcomeHeader = "영콘 월드"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."
